<?php

declare(strict_types=1);

namespace Semitexa\Core\Resource\Metadata;

use Semitexa\Core\Attribute\AsService;
use Semitexa\Core\Support\ProjectRoot;

#[AsService]
final class ResourceMetadataCacheFile
{
    public const RELATIVE_PATH = 'var/cache/resource-metadata.php';

    private ?string $absolutePath = null;

    /** Tests construct the cache file with an explicit path; container path stays null. */
    public static function forPath(string $absolutePath): self
    {
        $c = new self();
        $c->absolutePath = $absolutePath;
        return $c;
    }

    public function path(): string
    {
        if ($this->absolutePath !== null) {
            return $this->absolutePath;
        }

        return ProjectRoot::get() . '/' . self::RELATIVE_PATH;
    }

    public function exists(): bool
    {
        return is_file($this->path()) && is_readable($this->path());
    }

    /**
     * Phase 3d.5: hydrate a registry from the cache file when present, valid,
     * and matching the supplied fingerprint. Returns a structured result so
     * callers can distinguish:
     *
     *   - Hit     — payload valid AND fingerprint matches; registry hydrated.
     *   - Miss    — file does not exist.
     *   - Corrupt — file exists but its shape / payload version is unreadable.
     *   - Stale   — file is structurally valid but the recorded fingerprint
     *               disagrees with `$expectedFingerprint`.
     *
     * Pass `null` for `$expectedFingerprint` to skip the fingerprint check
     * (compatibility with callers that don't yet care, e.g. dev-mode tests).
     */
    public function loadWithResult(
        ResourceMetadataRegistry $registry,
        ?string $expectedFingerprint = null,
    ): CacheLoadResult {
        if (!$this->exists()) {
            return CacheLoadResult::Miss;
        }

        /** @var mixed $payload */
        $payload = require $this->path();
        if (!is_array($payload) || !isset($payload['version'], $payload['metadata']) || !is_array($payload['metadata'])) {
            return CacheLoadResult::Corrupt;
        }
        if ($payload['version'] !== 1) {
            return CacheLoadResult::Corrupt;
        }

        $recordedFingerprint = isset($payload['fingerprint']) && is_string($payload['fingerprint'])
            ? $payload['fingerprint']
            : null;

        if ($expectedFingerprint !== null) {
            // No recorded fingerprint on a payload that should have one →
            // pre-3d.5 cache. Treat as Stale so we rewrite with the new
            // payload shape rather than load it as-is.
            if ($recordedFingerprint === null) {
                return CacheLoadResult::Stale;
            }
            if (!hash_equals($expectedFingerprint, $recordedFingerprint)) {
                return CacheLoadResult::Stale;
            }
        }

        $registry->reset();
        foreach ($payload['metadata'] as $entry) {
            if (!is_array($entry)) {
                return CacheLoadResult::Corrupt;
            }
            $metadata = $this->hydrateObject($entry);
            if ($metadata === null) {
                return CacheLoadResult::Corrupt;
            }
            $registry->register($metadata);
        }

        return CacheLoadResult::Hit;
    }

    // Phase 6m: the pre-3d.5 boolean `load()` shim was removed for the
    // v1 release. Callers must use `loadWithResult(...)` so they can
    // distinguish Hit / Miss / Stale / Corrupt and act on each outcome
    // explicitly. Phase 6m's audit confirmed no production call site
    // relied on the boolean shim.

    /**
     * Dump the registry's contents into a deterministic PHP file.
     *
     * @param string|null $fingerprint Phase 3d.5: source fingerprint that the
     *                                  cache content was built from. Stored in
     *                                  the payload so a later load can detect
     *                                  source drift. Pass null only when the
     *                                  caller deliberately skips fingerprint
     *                                  protection (legacy / dev / tests).
     */
    public function dump(ResourceMetadataRegistry $registry, ?string $fingerprint = null): void
    {
        $entries = [];
        foreach ($registry->all() as $metadata) {
            $entries[] = $this->serializeObject($metadata);
        }

        $payload = [
            'version'     => 1,
            'fingerprint' => $fingerprint,
            'metadata'    => $entries,
        ];

        $php = "<?php\n\n// Auto-generated by Semitexa\\Core\\Resource\\Metadata\\ResourceMetadataCacheFile.\n// Do not edit by hand.\n\nreturn " . var_export($payload, true) . ";\n";

        $path = $this->path();
        $dir  = dirname($path);
        if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new \RuntimeException(sprintf(
                'ResourceMetadataCacheFile: cannot create directory %s',
                $dir,
            ));
        }

        // Atomic write: stage a sibling temp file, fsync, then rename. On POSIX
        // a same-directory rename is atomic, so a concurrent worker either
        // sees the old payload or the new one — never a half-written file.
        $tmp = $path . '.tmp.' . bin2hex(random_bytes(6));
        if (file_put_contents($tmp, $php, LOCK_EX) === false) {
            throw new \RuntimeException(sprintf(
                'ResourceMetadataCacheFile: cannot write staging file %s',
                $tmp,
            ));
        }
        @chmod($tmp, 0644);
        if (!@rename($tmp, $path)) {
            @unlink($tmp);
            throw new \RuntimeException(sprintf(
                'ResourceMetadataCacheFile: cannot rename %s to %s',
                $tmp,
                $path,
            ));
        }
    }

    public function delete(): bool
    {
        $path = $this->path();
        if (!is_file($path)) {
            return false;
        }

        return @unlink($path);
    }

    /** @return array<string, mixed> */
    private function serializeObject(ResourceObjectMetadata $metadata): array
    {
        $fields = [];
        foreach ($metadata->fields as $name => $field) {
            $fields[$name] = [
                'name'          => $field->name,
                'kind'          => $field->kind->value,
                'nullable'      => $field->nullable,
                'target'        => $field->target,
                'include'       => $field->include,
                'hrefTemplate'  => $field->hrefTemplate,
                'expandable'    => $field->expandable,
                'paginated'     => $field->paginated,
                'list'          => $field->list,
                'description'   => $field->description,
                'deprecated'    => $field->deprecated,
                'unionTargets'  => $field->unionTargets,
                'discriminator' => $field->discriminator,
                'resolverClass' => $field->resolverClass,
            ];
        }

        return [
            'class'       => $metadata->class,
            'type'        => $metadata->type,
            'idField'     => $metadata->idField,
            'fields'      => $fields,
            'description' => $metadata->description,
            'deprecated'  => $metadata->deprecated,
        ];
    }

    /** @param array<string, mixed> $entry */
    private function hydrateObject(array $entry): ?ResourceObjectMetadata
    {
        if (!isset($entry['class'], $entry['type'], $entry['fields'])
            || !is_string($entry['class'])
            || !is_string($entry['type'])
            || !is_array($entry['fields'])
        ) {
            return null;
        }

        $fields = [];
        foreach ($entry['fields'] as $name => $f) {
            if (!is_string($name) || !is_array($f) || !isset($f['kind']) || !is_string($f['kind'])) {
                return null;
            }
            $kind = ResourceFieldKind::tryFrom($f['kind']);
            if ($kind === null) {
                return null;
            }

            $fields[$name] = new ResourceFieldMetadata(
                name: (string) ($f['name'] ?? $name),
                kind: $kind,
                nullable: (bool) ($f['nullable'] ?? false),
                target: $this->nullableString($f['target'] ?? null),
                include: $this->nullableString($f['include'] ?? null),
                hrefTemplate: $this->nullableString($f['hrefTemplate'] ?? null),
                expandable: (bool) ($f['expandable'] ?? false),
                paginated: (bool) ($f['paginated'] ?? false),
                list: (bool) ($f['list'] ?? false),
                description: (string) ($f['description'] ?? ''),
                deprecated: (bool) ($f['deprecated'] ?? false),
                unionTargets: is_array($f['unionTargets'] ?? null) ? array_values(array_map('strval', $f['unionTargets'])) : null,
                discriminator: $this->nullableString($f['discriminator'] ?? null),
                resolverClass: $this->nullableString($f['resolverClass'] ?? null),
            );
        }

        /** @var class-string $class */
        $class = $entry['class'];

        return new ResourceObjectMetadata(
            class: $class,
            type: $entry['type'],
            idField: $this->nullableString($entry['idField'] ?? null),
            fields: $fields,
            description: (string) ($entry['description'] ?? ''),
            deprecated: (bool) ($entry['deprecated'] ?? false),
        );
    }

    private function nullableString(mixed $value): ?string
    {
        if ($value === null) {
            return null;
        }
        return is_string($value) ? $value : null;
    }
}
